//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCinema.resource.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLang_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KCinema.resource.localization.AppLang.ru", typeof(AppLang_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мультсериал.
        /// </summary>
        internal static string AnimatedSeries {
            get {
                return ResourceManager.GetString("AnimatedSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аниме.
        /// </summary>
        internal static string Anime {
            get {
                return ResourceManager.GetString("Anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мультфильм.
        /// </summary>
        internal static string Cartoon {
            get {
                return ResourceManager.GetString("Cartoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        internal static string ccountry {
            get {
                return ResourceManager.GetString("ccountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна: .
        /// </summary>
        internal static string cecountry {
            get {
                return ResourceManager.GetString("cecountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр: .
        /// </summary>
        internal static string cegenres {
            get {
                return ResourceManager.GetString("cegenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string cename {
            get {
                return ResourceManager.GetString("cename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг: .
        /// </summary>
        internal static string ceraiting {
            get {
                return ResourceManager.GetString("ceraiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премьера: .
        /// </summary>
        internal static string cereleaseDate {
            get {
                return ResourceManager.GetString("cereleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время просмотра: .
        /// </summary>
        internal static string cewatchTime {
            get {
                return ResourceManager.GetString("cewatchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to жанры.
        /// </summary>
        internal static string cgenres {
            get {
                return ResourceManager.GetString("cgenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to название.
        /// </summary>
        internal static string cname {
            get {
                return ResourceManager.GetString("cname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to страна.
        /// </summary>
        internal static string craiting {
            get {
                return ResourceManager.GetString("craiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to премьера.
        /// </summary>
        internal static string creleaseDate {
            get {
                return ResourceManager.GetString("creleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to время просмотра.
        /// </summary>
        internal static string cwatchTime {
            get {
                return ResourceManager.GetString("cwatchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to описание.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to почта.
        /// </summary>
        internal static string emailPlaceHolder {
            get {
                return ResourceManager.GetString("emailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильм.
        /// </summary>
        internal static string Film {
            get {
                return ResourceManager.GetString("Film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL&apos;s картинок.
        /// </summary>
        internal static string GalleryUrls {
            get {
                return ResourceManager.GetString("GalleryUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанры.
        /// </summary>
        internal static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англ\Ру.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пароль.
        /// </summary>
        internal static string passwordPlaceHolder {
            get {
                return ResourceManager.GetString("passwordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL постера.
        /// </summary>
        internal static string PosterUrl {
            get {
                return ResourceManager.GetString("PosterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премьера.
        /// </summary>
        internal static string Premier {
            get {
                return ResourceManager.GetString("Premier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        internal static string rating {
            get {
                return ResourceManager.GetString("rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сериал.
        /// </summary>
        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегестрироваться.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Светлая\Темная.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL трейлера.
        /// </summary>
        internal static string TrailerUrl {
            get {
                return ResourceManager.GetString("TrailerUrl", resourceCulture);
            }
        }
    }
}
